
language: node_js

node_js:
  - '12'

cache:
  yarn: true
  directories:
    - public
    - .cache

git:
  depth: 3

notifications:
  email:
    recipients:
      - aron_1991@live.com.ar
      - elsorbo1@gmail.com
      - josue.caballero.macias@outlook.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  commit_message: "Deploy del proyecto"
  
  on:
    branch: master
